name: Develop - UnitTests

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{vars.PYTHON_VERSION}}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests with coverage
        run: |
          pytest --cov=. --cov-fail-under=${{vars.TEST_COVER_MIN}} --cov-report=term-missing
